# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BootstrapCli < Formula
  desc "A minimalistic CLI to bootstrap projects with different frameworks."
  homepage "https://github.com/wingkwong/bootstrap-cli"
  version "0.1.0"
  license "MIT"

  depends_on "npm"
  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wingkwong/bootstrap-cli/releases/download/v0.1.0/bootstrap-cli_0.1.0_macOS_arm64.tar.gz"
      sha256 "a789b449c77404e0d4c0ed1da8003a52af6f5be7425008c649b9f2ecc6b7b7de"

      def install
        bin.install "bootstrap-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wingkwong/bootstrap-cli/releases/download/v0.1.0/bootstrap-cli_0.1.0_macOS_x86_64.tar.gz"
      sha256 "c2371cad7a0f867b1d5be39f836a88b654fae72721c324e384a9ccaa878d4497"

      def install
        bin.install "bootstrap-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wingkwong/bootstrap-cli/releases/download/v0.1.0/bootstrap-cli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "f9eeb8a4f7c2ae5e6df77eae45b717c1dfea75356f04383891508b65ca572f3d"

      def install
        bin.install "bootstrap-cli"
      end
    end
  end

  def caveats
    <<~EOS
      A minimalistic CLI to bootstrap projects with different frameworks.
    EOS
  end
end
